apiVersion: v1
kind: Service
metadata:
  name: nick-sagemaker-fastapi
  namespace: default
  labels:
    app: nick-sagemaker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: nick-sagemaker
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
